services:
  mariadb:
    image: mariadb:1.0
    build: ./requirements/mariadb
    networks: [inception]
    env_file: [./.env]
    restart: unless-stopped
    secrets: [db_password, db_root_password]
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    image: wordpress:1.0
    build: ./requirements/wordpress
    networks: [inception]
    env_file: [./.env]
    restart: unless-stopped
    secrets: [credentials, db_password]
    depends_on: [mariadb]
    volumes:
      - wordpress_volume:/var/www/html

  nginx:
    image: nginx:1.0
    build: ./requirements/nginx
    networks: [inception]
    restart: unless-stopped
    ports: ["443:443"]
    depends_on: [wordpress]
    volumes:
      - wordpress_volume:/var/www/html

  resume:
    image: resume:1.0
    build: ./requirements/bonus/resume
    networks: [inception]
    restart: unless-stopped
    ports: ["1337:1337"]

secrets:
    db_password:
      file: ../secrets/db_password.txt
    db_root_password:
      file: ../secrets/db_root_password.txt
    credentials:
      file: ../secrets/credentials.txt

networks:
  inception:

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/sel-jari/data/mariadb

  wordpress_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/sel-jari/data/wordpress
