server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name sel-jari.42.fr;

	ssl_certificate_key /etc/nginx/ssl/sel-jari.key;
	ssl_certificate /etc/nginx/ssl/sel-jari.crt;
	ssl_protocols TLSv1.2 TLSv1.3;

	# WordPress
	root /var/www/html/;

	#set index file
	index index.php;

	# forward PHP calls to FastCGI server
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
	}


	# bonus adminer
	location ^~ /adminer/ {
		include fastcgi_params;
		fastcgi_pass adminer:9000;
		fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
	}

	location = /adminer {
		return 301 /adminer/;
	}
}
